name: rootless-podman
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Podman (rootless) + docker shim
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq podman podman-docker uidmap slirp4netns fuse-overlayfs openssl curl
          pip install --user podman-compose
          echo "Podman compose version: $(podman-compose --version)"
          echo "Docker (shim) version: $(docker --version)"

      - name: Prepare environment
        run: |
          mkdir -p ./gateway/certs
          openssl req -x509 -newkey rsa:2048 -nodes \
            -keyout ./gateway/certs/localhost-key.pem \
            -out ./gateway/certs/localhost.pem \
            -days 365 -subj "/CN=localhost"

      - name: Run containers with :443 (should fail)
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cp .env.example .env.443
          sed -i 's/^GATEWAY_PORT=.*/GATEWAY_PORT=443/' .env.443

          if podman-compose --env-file .env.443 up -d --build 2>err.txt; then
            echo "[ ERROR ] Unexpected success: container bound to privileged port 443"
            podman ps
            podman-compose --env-file .env.443 down -v || true
            exit 1
          else
            echo "[ SUCCESS ] Expected failure when binding to port 443 (rootless Podman restriction)"
            head -n 40 err.txt || true
            podman-compose --env-file .env.443 down -v || true
          fi

      - name: Run containers with :8443 (should pass)
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          cp .env.example .env.8443
          sed -i 's/^GATEWAY_PORT=.*/GATEWAY_PORT=8443/' .env.8443

          podman-compose --env-file .env.8443 up -d --build
          podman ps

          for i in {1..40}; do
            if curl -kfsS "https://127.0.0.1:8443" >/dev/null 2>&1; then
              echo "[ SUCCESS ] Gateway reachable on 8443"
              break
            fi
            sleep 0.5
          done

          podman-compose --env-file .env.8443 down -v || true

      - name: Cleanup
        if: always()
        run: podman down -v || true
